//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDepotWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSet
    {
        public int Id { get; set; }
        public System.DateTime Afhentningstid { get; set; }
        public int Antaldage { get; set; }
        public int KundeId { get; set; }
        public int VærktøjId { get; set; }
        public string Status { get; set; }
    
        public virtual KundeSet KundeSet { get; set; }
        public virtual VærktøjSet VærktøjSet { get; set; }

        public string ListBoxToString
        {
            get
            {
                return $"{VærktøjSet.Navn}: Afhentning: {Afhentningstid} Antal dage: {Antaldage} Depositum: {VærktøjSet.Depositum}  Døgnpris: {VærktøjSet.Døgnpris}";
            }
        }
    }
}
