//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDepotWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VærktøjSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VærktøjSet()
        {
            this.BookingSets = new HashSet<BookingSet>();
        }
    
        public int Id { get; set; }
        public string Navn { get; set; }
        public string Beskrivelse { get; set; }
        public double Depositum { get; set; }
        public double Døgnpris { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingSet> BookingSets { get; set; }

        public string prinVærktøj
        {
            get
            {
                return $"{Navn}: {Beskrivelse} Depositum: {Depositum}: Døgnpris: {Døgnpris}";
            }
        }
    }
}
